arm_controller:
  type: follow_joint_trajectory/JointTrajectoryController
  joints:
    - base_to_second
    - second_to_third
    - third_to_fourth
    - fourth_to_fifth
    - fifth_to_sixth

joint_limits:
  base_to_second:
    has_position_limits: true
    min_position: -0.5
    max_position: 0.1
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    has_jerk_limits: false
    has_effort_limits: true
    max_effort: 4.0
  second_to_third:
    has_position_limits: true
    min_position: -1.5
    max_position: 0.8
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    has_jerk_limits: false
    has_effort_limits: true
    max_effort: 4.0
  third_to_fourth:
    has_position_limits: true
    min_position: -0.4
    max_position: 0.4
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    has_jerk_limits: false
    has_effort_limits: true
    max_effort: 4.0
  fourth_to_fifth:
    has_position_limits: true
    min_position: -1.0
    max_position: 1.5
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    has_jerk_limits: false
    has_effort_limits: true
    max_effort: 4.0
  fifth_to_sixth:
    has_position_limits: true
    min_position: -0.8
    max_position: 0.8
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    has_jerk_limits: false
    has_effort_limits: true
    max_effort: 4.0
