controller_list:
  - name: /kyun/joint_state_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - joint_state_controller
      - joint1_position_controller
      - joint2_position_controller
      - joint3_position_controller
      - joint4_position_controller
      - joint5_position_controller
