controller_list:
  - name:  arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - base_to_2nd
      - 2nd_to_3rd
      - 3rd_to_4th
      - 4th_to_5th
      - 5th_to_6th
