# Publish all joint states
joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 250

arm_controller:
  type: "position_controllers/JointTrajectoryController"
  publish_rate: 250
  joints:
    - world_to_base
    - base_to_2nd
    - 2nd_to_3rd
    - 3rd_to_4th
    - 4th_to_5th
    - 5th_to_6th

  constraints:
    goal_time: 0.0
    stopped_velocity_tolerance: 1.0

dynamixel_port:
  port_name: "/dev/ttyUSB3"
  baud_rate: 57600
  joints:
    - world_to_base
    - base_to_2nd
    - 2nd_to_3rd
    - 3rd_to_4th
    - 4th_to_5th
    - 5th_to_6th
  base_to_2nd: {id: 3, center: 2048, home: 2048, effort_const: 1.79, mode: 3 }
  2nd_to_3rd: {id: 4, center: 2048, home: 2048, effort_const: 1.79, mode: 3 }
  3rd_to_4th: {id: 1, center: 2048, home: 2048, effort_const: 1.79, mode: 3 }
  4th_to_5th: {id: 2, center: 2048, home: 2048, effort_const: 1.79, mode: 3 }
  5th_to_6th: {id: 5, center: 2048, home: 2048, effort_const: 1.79, mode: 3 }

joint_limits:
  base_to_2nd:
    has_position_limits: true
    min_position: -1.5707963268
    max_position: 1.5707963268
    has_velocity_limits: true
    max_velocity: 5.969211435
    has_acceleration_limits: false
    has_jerk_limits: false
    has_effort_limits: true
    max_effort: 4.0
  2nd_to_3rd:
    has_position_limits: true
    min_position: -1.5707963268
    max_position: 0.0
    has_velocity_limits: true
    max_velocity: 5.969211435
    has_acceleration_limits: false
    has_jerk_limits: false
    has_effort_limits: true
    max_effort: 4.0
  3rd_to_4th:
    has_position_limits: true
    min_position: -1.5707963268
    max_position: 1.5707963268
    has_velocity_limits: true
    max_velocity: 5.969211435
    has_acceleration_limits: false
    has_jerk_limits: false
    has_effort_limits: true
    max_effort: 4.0
  4th_to_5th:
    has_position_limits: true
    min_position: 0.0
    max_position: 2.726204
    has_velocity_limits: true
    max_velocity: 5.969211435
    has_acceleration_limits: false
    has_jerk_limits: false
    has_effort_limits: true
    max_effort: 4.0
  5th_to_6th:
    has_position_limits: true
    min_position: -1.5707963268
    max_position: 1.5707963268
    has_velocity_limits: true
    max_velocity: 5.969211435
    has_acceleration_limits: false
    has_jerk_limits: false
    has_effort_limits: true
    max_effort: 4.0
