joints: ['pan_joint', 'tilt_joint']

# パン(水平方向の回転)用サーボモータの設定
pan_joint:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController 
    joint_name: pan_joint
    joint_speed: 1.2
    motor:
        id: 1
        init: 512
        min: 0
        max: 1023

# チルト（垂直方向の回転）用サーボモータの設定
tilt_joint:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController 
    joint_name: tilt_joint
    joint_speed: 1.2
    motor:
        id: 2
        init: 512
        min: 0
        max: 1023
