# Publish all joint states
joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 250

arm_controller:
  type: "position_controllers/JointTrajectoryController"
  publish_rate: 250
  joints:
    - base_to_second
    - second_to_third
    - third_to_fourth
    - fourth_to_fifth
    - fifth_to_sixth
  constraints:
    goal_time: 0.0
    stopped_velocity_tolerance: 1.0

dynamixel_port:
  port_name: "/dev/ttyUSB3"
  baud_rate: 57600
  joints:
    - base_to_second
    - second_to_third
    - third_to_fourth
    - fourth_to_fifth
    - fifth_to_sixth
  base_to_second: {id: 3, center: 2048, home: 2048, effort_const: 1.79, mode: 3 }
  second_to_third: {id: 4, center: 2048, home: 2048, effort_const: 2.79, mode: 3 }
  third_to_fourth: {id: 1, center: 2048, home: 2048, effort_const: 1.79, mode: 3 }
  fourth_to_fifth: {id: 2, center: 2048, home: 2048, effort_const: 1.79, mode: 3 }
  fifth_to_sixth: {id: 5, center: 2048, home: 2048, effort_const: 1.79, mode: 3 }
